version: '3.8'

services:
  birthday-notifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birthday-notifier
    env_file: .env
    restart: always
    # Para acceder a la red del host (si la BD está en host.docker.internal)
    # network_mode: host
    # O descomenta para usar bridge con la red del host
    # networks:
    #   - crons_network
